### ISSUE TITLE
✨ 응답 구조 변경을 위한 코드 작성

### ISSUE THREAD

**Issue by MinseoKangQ** [SumNote/sumnote-kopring-server#48]
### 🤓 TODO
- [ ] Base 응답 클래스 작성
- [ ] Error 관련 코드 작성
- [ ] Exception 관련 코드 작성
- [ ] 테스트 컨트롤러에 적용 후 테스트
 

<br>

### ⏱️ 마감기한
- 1/4(토)
